config/routes.rb
Shopping::Application.routes.draw do
  resources :components

  match '/' => 'categories#index'

  resources :sub_categories

  resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
 has_many :sub_categories
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    @sub_categories = SubCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :ok }
    end
  end
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  # GET /sub_categories
  # GET /sub_categories.json
  def index
    @sub_categories = SubCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sub_categories }
    end
  end

  # GET /sub_categories/1
  # GET /sub_categories/1.json
  def show
    @sub_category = SubCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sub_category }
    end
  end

  # GET /sub_categories/new
  # GET /sub_categories/new.json
  def new
    @sub_category = SubCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sub_category }
    end
  end

  # GET /sub_categories/1/edit
  def edit
    @sub_category = SubCategory.find(params[:id])
  end

  # POST /sub_categories
  # POST /sub_categories.json
  def create
    @sub_category = SubCategory.new(params[:sub_category])

    respond_to do |format|
      if @sub_category.save
        format.html { redirect_to @sub_category, notice: 'Sub category was successfully created.' }
        format.json { render json: @sub_category, status: :created, location: @sub_category }
      else
        format.html { render action: "new" }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sub_categories/1
  # PUT /sub_categories/1.json
  def update
    @sub_category = SubCategory.find(params[:id])

    respond_to do |format|
      if @sub_category.update_attributes(params[:sub_category])
        format.html { redirect_to @sub_category, notice: 'Sub category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_categories/1
  # DELETE /sub_categories/1.json
  def destroy
    @sub_category = SubCategory.find(params[:id])
    @sub_category.destroy

    respond_to do |format|
      format.html { redirect_to sub_categories_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  -if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
-#%ul
  .categories
  -@categories.each do |category|
    %li
      %a{:href=>"",:title =>"= category.name"}
        %strong
          = category.name

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_category_path(@category)
\|
= link_to 'Back', categories_path

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta http-equiv="Content-Style-Type" content="text/css">
  <title>Shopping</title>
  <meta name="Generator" content="Cocoa HTML Writer">
  <meta name="CocoaVersion" content="1038.36">
  <style type="text/css">
    p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Times}
    p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Courier}
    p.p3 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Times; min-height: 14.0px}
  </style>
</head>
<body>
<p class="p1">
<%=stylesheet_link_tag "application" %>
<%= javascript_include_tag "application" %> <%= csrf_meta_tags%>
</p>
<div id="page">
<ul class="categories">
  <% @categories.each do |category| %>
  <% if category.parent_id==nil %>
  <li>
    <a href="" title ="<%=category.name%>" rel ="<%=category.id%>"><%=category.name%></a>
    <%  id=category.id %>
    <ul class="sub" id="<%=category.name%>">
      <% @categories.each do |sb| %>
      <% if sb.parent_id==id %>
         <li>
           <a href=""  title="<%= sb.name.to_s+sb.id.to_s%>"><%= sb.name%></a>
           <ul class="sub_nav" id="<%= sb.name.to_s+sb.id.to_s%>">
             <% @categories.each do |nav| %>
             <% if nav.parent_id==sb.id %>
                <li>
                  <a href=""  title=""><%= nav.name %></a>
                </li>
             <%end %>
             <%end %>
           </ul>
         </li>
      <%end %>
      <%end %>
    </ul>
  </li> 
  <% end %>
  <% end %>
</ul>

    
    


<%= yield %>
</div>
</body>
</html>

app/views/sub_categories/_form.html.haml
= form_for @sub_category do |f|
  -if @sub_category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@sub_category.errors.count, "error")} prohibited this sub_category from being saved:"
      %ul
        - @sub_category.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/sub_categories/edit.html.haml
%h1 Editing sub_category

= render 'form'

= link_to 'Show', @sub_category
\|
= link_to 'Back', sub_categories_path

app/views/sub_categories/index.html.haml
%h1 Listing sub_categories

%table
  %tr
    %th
    %th
    %th

  - @sub_categories.each do |sub_category|
    %tr
      %td= link_to 'Show', sub_category
      %td= link_to 'Edit', edit_sub_category_path(sub_category)
      %td= link_to 'Destroy', sub_category, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Sub category', new_sub_category_path

app/views/sub_categories/new.html.haml
%h1 New sub_category

= render 'form'

= link_to 'Back', sub_categories_path

app/views/sub_categories/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_sub_category_path(@sub_category)
\|
= link_to 'Back', sub_categories_path